behaviors:
  Park90RC:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 5120
      learning_rate: 0.0003
      beta: 0.0025
      epsilon: 0.3
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1


    keep_checkpoints: 15
    checkpoint_interval: 500000
    time_horizon: 264
    max_steps: 50000000
    summary_freq: 20000
    threaded: true
